<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- wheel defining macro -->
  <xacro:macro name="wheel" params="wheel_radius wheel_separation_y prefix">

    <xacro:property name="wheel_separation_x" value="0.170" />
    <xacro:property name="wheel_thickness" value="0.032" />

    <xacro:if value="${prefix == 'fl'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="file://$(find rosbot_xl_description)/meshes/wheel_a.dae" />
    </xacro:if>
    <xacro:if value="${prefix == 'fr'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="-${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="file://$(find rosbot_xl_description)/meshes/wheel_b.dae" />
    </xacro:if>
    <xacro:if value="${prefix == 'rl'}">
      <xacro:property name="x" value="-${wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="file://$(find rosbot_xl_description)/meshes/wheel_a.dae" />
    </xacro:if>
    <xacro:if value="${prefix == 'rr'}">
      <xacro:property name="x" value="-${wheel_separation_x/2}" />
      <xacro:property name="y" value="-${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="file://$(find rosbot_xl_description)/meshes/wheel_b.dae" />
    </xacro:if>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="body_link" />
      <child link="${prefix}_wheel_link" />
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0.0 1.0 0.0" />

      <limit effort="1.2" velocity="21.0" />

      <dynamics damping="0.001" friction="0.001" />
    </joint>

    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <mesh filename="${mesh}" scale="1 1 1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
        <surface>
          <!-- Surface settings based on https://github.com/gazebosim/gz-sim/blob/gz-sim7/examples/worlds/diff_drive_skid.sdf -->
          <friction>
            <ode>
              <mu>0.5</mu>
              <mu2>1.0</mu2>
              <fdir1>0 0 1</fdir1>
            </ode>
            <bullet>
              <friction>1</friction>
              <friction2>1</friction2>
              <rolling_friction>0.1</rolling_friction>
            </bullet>
          </friction>
        </surface>
      </collision>

      <inertial>
        <mass value="0.051" />
        <inertia  ixx="3.954e-05" ixy="0.000"     ixz="0.000"
                                  iyy="7.116e-05" iyz="0.000"
                                                  izz="4.032e-05" />
      </inertial>
    </link>

  </xacro:macro>
</robot>