controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # rosbot_xl_hardware_controller:
    #   type: rosbot_xl_controllers/RosbotXLSystem

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
