
# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

version: "2.3"

services:

  # ROS Galactic
  rviz:
    image: husarion/rviz2
    restart: unless-stopped
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./rviz_docker_config/rbxl.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY