
# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml up

version: "2.3"

services:

  # ROS Galactic
  rviz:
    network_mode: host
    ipc: host
    # environment:
    #   - ROS_DOMAIN_ID=138