services:
  # ROS Foxy Rviz2 VNC
  rviz2:
    image: husarion/ros2-desktop-vnc:latest
    restart: on-failure
    logging:
      driver: none
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/cyclonedds.xml
      - ./rviz_docker_config/pusher.rviz:/root/.rviz2/default.rviz
      - ./rviz_docker_config/.bash_history:/root/.bash_history
    shm_size: '512m'
    runtime: nvidia
    ports:
      - 6080:80