services:
  # ROS Foxy navigation
  nav2:
    image: husarion/nav2:galactic
    tty: true
    restart: on-failure
    volumes:
      - ./husarion_nav2_config:/app/ros2_ws/src/husarion_nav2/config
    command: ros2 launch husarion_nav2 bringup_both.launch.py

  # ROS Foxy Rviz2 VNC
  rviz2:
    image: husarion/ros2-desktop-vnc:latest
    restart: on-failure
    logging:
      driver: none
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - ./rviz_docker_config/pusher.rviz:/root/.rviz2/default.rviz
      - ./rviz_docker_config/.bash_history:/root/.bash_history
    shm_size: '512m'
    runtime: nvidia
    ports:
      - 6080:80