controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    rosbot_xl_base_controller:
      type: diff_drive_controller/DiffDriveController

rosbot_xl_base_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    # Should be in urdf
    # wheel_separation: 0.10
    # wheel_radius: 0.015

    # TODO: confirm it (if it should be like that for skid kinematics)
    wheel_separation_multiplier: 1.5
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0 # m/s
        min_velocity: -1.0 # m/s
        max_acceleration: 1.0 # m/s^2
        max_jerk: 0.0 # m/s^3
        min_jerk: 0.0 # m/s^3

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        has_jerk_limits: false
        max_velocity: 1.0 # rad/s
        min_velocity: -1.0 # rad/s
        max_acceleration: 1.0 # rad/s^2
        min_acceleration: -1.0 # rad/s^2
        max_jerk: 0.0 # rad/s^3
        min_jerk: 0.0 # rad/s^3
