<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- body defining macro -->
  <xacro:macro name="body" params="wheel_diameter">

    <link name="base_link"></link> 

    <link name="body_link">
      <visual>
        <geometry>
          <mesh filename="package://rosbot_xl_description/models/rosbot_xl_base/meshes/body.dae" scale="1 1 1"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </visual>

      <collision>
        <geometry>
          <mesh filename="package://rosbot_xl_description/models/rosbot_xl_base/meshes/body_colision.stl" scale="1 1 1" />
        </geometry>
        <origin xyz="0.0 0.0 0.00" rpy="0.0 0.0 0.0"/>
      </collision>

      <inertial>
          <mass value="3.0" />
          <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                             iyy="1.0" iyz="0.0"
                                       izz="0.0" />
      </inertial>
    </link>

    <link name="cover_link">
      <inertial>
        <mass value="0.0000001" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                           iyy="1.0" iyz="0.0"
                                     izz="0.0" />
      </inertial>
    </link> 

    <link name="imu_link">
      <inertial>
        <mass value="0.0000001" />
        <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1" />
      </inertial>
    </link>


    <joint name="base_link_to_body_joint" type="fixed">
      <origin xyz="0.0 0.0 ${wheel_diameter/2}" rpy="0.0 0.0 0.0" />
      <parent link="base_link" />
      <child link="body_link" />
    </joint>

    <joint name="body_to_cover_joint" type="fixed">
      <origin xyz="0.0 0.0 0.08345" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="cover_link" />
    </joint>

    <joint name="body_link_to_imu_link_joint" type="fixed">
      <origin xyz="-0.1369 -0.0419 0.0370" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="imu_link" />
    </joint>
  
  </xacro:macro>

</robot>