<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- body defining macro -->
  <xacro:macro name="body" params="wheel_diameter">

    <link name="base_link"></link> 

    <link name="body_link">
      <visual>
        <geometry>
          <mesh filename="file://$(find rosbot_xl_description)/models/rosbot_xl_base/meshes/body.dae" scale="1 1 1"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </visual>

      <collision>
        <geometry>
          <mesh filename="file://$(find rosbot_xl_description)/models/rosbot_xl_base/meshes/body_colision.stl" scale="1 1 1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </collision>

      <inertial>
        <mass value="3.5" />
        <origin xyz="-0.016319 -0.004036 0.02819" rpy="0.0 0.0 0.0"/>
        <inertia ixx="0.0254042524427888" ixy="-0.0002000608350169362" ixz="-0.0009754256573561553"
                                          iyy="0.028746423126319035"   iyz="-0.0002603325647592511"
                                                                       izz="0.046227102375569866" />
      </inertial>                             
    </link>

    <link name="cover_link"></link> 
    <link name="imu_link"></link>

    <joint name="base_link_to_body_joint" type="fixed">
      <origin xyz="0.0 0.0 ${wheel_diameter/2}" rpy="0.0 0.0 0.0" />
      <parent link="base_link" />
      <child link="body_link" />
    </joint>

    <joint name="body_to_cover_joint" type="fixed">
      <origin xyz="0.0 0.0 0.08345" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="cover_link" />
    </joint>

    <joint name="body_link_to_imu_link_joint" type="fixed">
      <origin xyz="-0.1369 -0.0419 0.0370" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="imu_link" />
    </joint>
  
  </xacro:macro>

</robot>