<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- wheel defining macro -->
  <xacro:macro name="wheel" params="wheel_type prefix">

    <xacro:property name="wheel_separation_x" value="0.170" />
    <xacro:property name="wheel_separation_y" value="0.236" />
    <xacro:property name="wheel_diameter" value="0.082" />
    <xacro:property name="wheel_thickness" value="0.032" />

    <xacro:if value="${prefix == 'front_left'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://rosbot_xl_description/models/rosbot_xl_base/meshes/wheel_a.dae" />
    </xacro:if>
    <xacro:if value="${prefix == 'front_right'}">
      <xacro:property name="x" value="${wheel_separation_x/2}" />
      <xacro:property name="y" value="-${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://rosbot_xl_description/models/rosbot_xl_base/meshes/wheel_b.dae" />
    </xacro:if>
    <xacro:if value="${prefix == 'rear_left'}">
      <xacro:property name="x" value="-${wheel_separation_x/2}" />
      <xacro:property name="y" value="${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://rosbot_xl_description/models/rosbot_xl_base/meshes/wheel_a.dae" />
    </xacro:if>
    <xacro:if value="${prefix == 'rear_right'}">
      <xacro:property name="x" value="-${wheel_separation_x/2}" />
      <xacro:property name="y" value="-${wheel_separation_y/2}" />
      <xacro:property name="mesh" value="package://rosbot_xl_description/models/rosbot_xl_base/meshes/wheel_b.dae" />
    </xacro:if>


    <link name="${prefix}_wheel_link">
       <visual>
        <geometry>
          <mesh filename="${mesh}" scale="1 1 1" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_thickness}"/>
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0" />
      </collision>

      <inertial>
          <mass value="0.100" />
          <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                             iyy="1.0" iyz="0.0"
                                       izz="0.0" />
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="body_link" />
      <child link="${prefix}_wheel_link" />
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0.0 1.0 0.0" />

      <limit effort="2.0"
             velocity="5.0" />

      <dynamics damping="0.1"
                friction="0.1"/>
    </joint>


    <gazebo reference="${prefix}_wheel_link">
      <mu1 value="0.5" />
      <mu2 value="0.5" />
      <kp value="10000000.0" />
      <kd value="1.0" />
      <fdir1 value="1 0 0"/>
    </gazebo>
    
    
  </xacro:macro>

</robot>