services:
  ros-master:
    image: ros:melodic-ros-core
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
    command: roscore

  # ROS Noetic + ROS 2 Galactic
  bridge:
    image: ros:galactic-ros1-bridge
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_DOMAIN_ID=0"
    command: ros2 run ros1_bridge dynamic_bridge

  microros:
    image: husarion/micro-ros-agent
    environment:
      - "ROS_DOMAIN_ID=0"
    network_mode: host
    ipc: host
    # ports:
    #   - "8888:8888/udp"
    command: udp4 --port 8888

  rosbot_xl:
    build:
      context: ./../
      dockerfile: ./hardware/Dockerfile
    container_name: rosbot_xl_ros
    network_mode: host
    ipc: host
    environment:
      - "ROS_DOMAIN_ID=0"
    volumes:
      - ../src/rosbot_xl_ekf:/app/ros2_ws/src/rosbot_xl_ekf
      # - ./src/rosbot_xl_hardware:/app/ros2_ws/src/rosbot_xl_hardware
      - ../src/rosbot_xl_description:/app/ros2_ws/src/rosbot_xl_description
      - ../src/rosbot_xl_kinematics:/app/ros2_ws/src/rosbot_xl_kinematics
    command: ros2 run rosbot_xl_kinematics classic_kinematics

  ros-rplidar:
    image: husarion/rplidar:latest
    devices:
      - /dev/ttyUSB0
    network_mode: host
    ipc: host
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
    tty: true        # docker run -t
    command: roslaunch rplidar_ros rplidar_s1.launch --wait