# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.yaml -f compose.rosbot.husarnet.yaml up

services:
  rosbot-xl:
    network_mode: service:husarnet
    # ipc: service:husarnet
    volumes:
      # - ./dds-config.server.xml:/dds-config.xml
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  microros:
    network_mode: service:husarnet
    # ipc: service:husarnet
    # ports:
    #   - "8888:8888/udp"
    volumes:
      # - ./dds-config.client.xml:/dds-config.xml
      - ./dds-config.xml:/dds-config.xml
      - ./micro-ros_entrypoint.sh:/micro-ros_entrypoint.sh
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  nav2:
    network_mode: service:husarnet
    # ipc: service:husarnet
    volumes:
      # - ./dds-config.client.xml:/dds-config.xml
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  rplidar:
    network_mode: service:husarnet
    # ipc: service:husarnet
    volumes:
      # - ./dds-config.client.xml:/dds-config.xml
      - ./dds-config.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    # ipc: shareable
    ports:
      - "8888:8888/udp"
    volumes:
      - /var/lib/husarnet
      - ./id:/var/lib/husarnet/id
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosbot-xl
      - JOINCODE=${HUSARNET_JOINCODE}