services:
  rosbot_xl:
    build:
      context: ./..
      dockerfile: ./Dockerfile.simulation
    # image: husarion/rosbot-xl:galactic-simulation
    container_name: rosbot_xl
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../src:/ros2_ws/src
    command: ros2 launch rosbot_xl_gazebo sim.launch.py

  nav2:
    image: husarion/nav2:galactic
    restart: unless-stopped
    volumes:
      - ../config/nav2:/ros2_ws/src/husarion_nav2/config
    command: >
      ros2 launch husarion_nav2 navigation2_bringup.launch.py
        use_slam:=True 
        use_auto_localization:=False
        use_sim_time:=True


  rviz:
    image: husarion/rviz2:galactic
    restart: unless-stopped
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../config/rviz/rbxl.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY