# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml -f compose.pc.lan.yaml -f compose.pc-nvidia.yaml up

services:
  rviz:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all