
# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml -f compose.pc.lan.yaml up

services:

  # ROS Galactic
  rviz:
    network_mode: host
    ipc: host
    # environment:
    #   - ROS_DOMAIN_ID=138