services:
  rosbot_xl:
    build:
      context: ./..
      dockerfile: ./Dockerfile.simulation
    # image: husarion/rosbot-xl:galactic-simulation
    container_name: rosbot_xl
    runtime: nvidia
    tty: true
    stdin_open: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./../src:/ros2_ws/src
    command: watch ls
    # command: ros2 launch rosbot_xl_gazebo sim.launch.py
