# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.yaml up

services:
  nav2:
    image: husarion/nav2:galactic
    restart: unless-stopped
    volumes:
      # - nav2config:/ros2_ws/src/husarion_nav2/config:ro
      - ./../config/nav2:/ros2_ws/src/husarion_nav2/config
    command: ros2 launch husarion_nav2 bringup_both.launch.py

  microros:
    image: microros/micro-ros-agent:galactic
    restart: unless-stopped
    command: udp4 --port 8888

  rosbot-xl:
    build:
      context: ./../
      dockerfile: ./Dockerfile.hardware
    # image: husarion/rosbot-xl:galactic
    # volumes:
    #   - nav2config:/config/nav2:ro
    restart: unless-stopped
    command: ros2 launch rosbot_xl_bringup diff_drive.launch.py
    # command: sleep 3600

  rplidar:
    image: husarion/rplidar:galactic
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
    command: ros2 launch rplidar_ros2 rplidar_s1_launch.py inverted:=true

volumes:
  nav2config: