# Quick Start (at fist stop ROS Master if working on host)
# $ docker compose -f compose.rosbot.yaml -f compose.rosbot.husarnet.yaml up

services:
  # ROS Galactic
  nav2:
    network_mode: service:husarnet
    volumes:
      - ./dds-config1.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  # ROS Galactic
  microros:
    network_mode: service:husarnet
    # ports:
    #   - "8888:8888/udp"
    volumes:
      - ./dds-config1.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  # ROS 2 Galacitc
  rosbot_xl:
    network_mode: service:husarnet
    volumes:
      - ./dds-config1.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  # ROS Noetic + ROS 2 Galactic
  bridge:
    network_mode: service:husarnet
    volumes:
      - ./dds-config1.xml:/dds-config.xml
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml

  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    ports:
      - "8888:8888/udp"
    volumes:
      - /var/lib/husarnet 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rosbot-xl
      - JOINCODE=${HUSARNET_JOINCODE}