# Quick Star
# $ docker compose -f compose.rosbot.yaml up

services:
  rosbot-xl:
    image: husarion/rosbot-xl:galactic
    # build:
    #   context: ./../
    #   dockerfile: ./Dockerfile.hardware
    restart: unless-stopped
    command: ros2 launch rosbot_xl_bringup bringup.launch.py

  microros:
    image: microros/micro-ros-agent:galactic
    restart: unless-stopped
    command: udp4 --port 8888

  # modified behaviour tree that doesn't replane global path
  nav2:
    image: husarion/navigation2:galactic
    restart: unless-stopped
    volumes:
      - ../config/nav2_params.yaml:/nav2_params.yaml
      - ../config/navigate_w_recovery.xml:/navigate_w_recovery.xml
    command: >
      ros2 launch nav2_bringup navigation_launch.py    
        params_file:=/nav2_params.yaml

  slam-toolbox:
    image: husarion/slam-toolbox:galactic
    restart: unless-stopped
    volumes:
      - ../config/slam_toolbox_params.yaml:/slam_params.yaml
      # - ./maps:/maps
    command: >
      ros2 launch slam_toolbox online_sync_launch.py 
        slam_params_file:=/slam_params.yaml

  rplidar:
    image: husarion/rplidar:galactic
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
    command: ros2 launch rplidar_ros2 rplidar_s1_launch.py inverted:=true
