
# Quick Start
# $ xhost local:root
# $ docker compose -f compose.pc.yaml -f compose.pc.husarnet.yaml up

services:

  # ROS Galactic
  rviz:
    network_mode: service:husarnet
    volumes:
      # - ./dds-config.client.xml:/dds-config.xml
      - ./dds-config.xml:/dds-config.xml
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      # - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
      - CYCLONEDDS_URI=file:///dds-config.xml

  husarnet:
    image: husarnet/husarnet
    restart: unless-stopped
    volumes:
      - /var/lib/husarnet 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=rviz2
      - JOINCODE=${HUSARNET_JOINCODE}