name: Build a Docker Image

on:
  push:
    branches:
      - 'ros-control-hardware'
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/arm64
        push: true
        tags: ghcr.io/husarion/rosbot-xl
        cache-from: type=registry,ref=ghcr.io/husarion/rosbot-xl:buildcache
        cache-to: type=registry,ref=ghcr.io/husarion/rosbot-xl:buildcache,mode=max