---
name: Industrial CI
on:
    workflow_call:
    workflow_dispatch:
    push:


jobs:
    black_test:
        uses: ./.github/workflows/black.yaml

    spellcheck_test:
        uses: ./.github/workflows/spellcheck.yaml

    industrial_ci:
        needs:
            - black_test
            - spellcheck_test
        strategy:
            fail-fast: false
            matrix:
                ROS_DISTRO: [humble]
        runs-on: ubuntu-latest
        timeout-minutes: 12
        steps:
            - uses: actions/checkout@v3
            - name: Clone installation requirements
              shell: bash
              run: python3 -m pip install -U vcstool && vcs import . < ./rosbot_xl/rosbot_xl_hardware.repos && vcs import . < ./rosbot_xl/rosbot_xl_simulation.repos
            - uses: ros-industrial/industrial_ci@master
              env:
                  ROS_DISTRO: ${{matrix.ROS_DISTRO}}
